#Author: Balaji N
#Date: 27-06-2023
#Description: This workflow will uses the reusable worklfow template to perform the task.

name: "Testing Secrets"
on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

permissions:
  contents: write

jobs:
  SecretsTest:
    uses: /bnrrb/ReusableWorkflow/.github/workflows/SecretsTest.yml@main
    with:
      GitHubActionRunner: "windows-latest"
